.TH "dirh" 1 "Mon Jul 6 2015" "Version 2.2.0" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
\fBdirh\fP -- print directory history 

.PP
.SS "Synopsis"
.PP
.nf

\fBdirh\fP
.fi
.PP
.SS "Description"
\fCdirh\fP prints the current directory history\&. The current position in the history is highlighted using the color defined in the \fCfish_color_history_current\fP environment variable\&.
.PP
\fCdirh\fP does not accept any parameters\&. 
