.TH "dirs" 1 "Mon Jul 6 2015" "Version 2.2.0" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
\fBdirs\fP -- print directory stack 

.PP
.SS "Synopsis"
.PP
.nf

\fBdirs\fP
.fi
.PP
.SS "Description"
\fCdirs\fP prints the current directory stack, as created by the \fC\fCpushd\fP\fP command\&.
.PP
\fCdirs\fP does not accept any parameters\&. 
