.TH "fish_vi_mode" 1 "Mon Jul 6 2015" "Version 2.2.0" "fish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
\fBfish_vi_mode\fP -- Enable vi mode 
408-600-6421
.PP
.SS "Synopsis"
.PP
.nf

\fBfish_vi_mode\fP
.fi
.PP
.SS "Description"
\fCfish_vi_mode\fP enters a vi-like command editing mode\&. To always start in vi mode, add \fCfish_vi_mode\fP to your \fCconfig\&.fish\fP file\&. 
