# alternatives
# Autogenerated from man page /usr/share/man/man8/alternatives.8.gz
# using Deroffing man parser
complete -c alternatives -l verbose --description 'Generate more comments about what  alternatives is doing.'
complete -c alternatives -l quiet --description 'Don\'t generate any comments unless errors occur.'
complete -c alternatives -l test --description 'Don\'t actually do anything, just say what would be done.'
complete -c alternatives -l help --description 'Give some usage information (and say which vers… [See Man Page]'
complete -c alternatives -l version --description 'Tell which version of  alternatives this is (an… [See Man Page]'
complete -c alternatives -l altdir --description 'Specifies the alternatives directory, when this… [See Man Page]'
complete -c alternatives -l admindir --description 'Specifies the administrative directory, when th… [See Man Page]'
complete -c alternatives -l install --description 'Add a group of alternatives to the system.'
complete -c alternatives -l remove --description 'Remove an alternative and all of its associated slave links.'
complete -c alternatives -l set --description 'The symbolic link and slaves for link group nam… [See Man Page]'
complete -c alternatives -l config --description 'Present the user with a configuration menu for … [See Man Page]'
complete -c alternatives -l auto --description 'Switch the master symlink  name to automatic mode.'
complete -c alternatives -l initscript --description 'is a Red Hat Linux specific option.  Zero or more.'
complete -c alternatives -l slave --description 'options, each followed by three arguments, may be specified.'
complete -c alternatives -l display --description 'Display information about the link group of whi… [See Man Page]'

