# cal
# Autogenerated from man page /usr/share/man/man1/cal.1.gz
# using Deroffing man parser
complete -c cal -s 1 -l one --description 'Display single month output.  (This is the default. ).'
complete -c cal -s 3 -l three --description 'Display three months spanning the date.'
complete -c cal -s s -l sunday --description 'Display Sunday as the first day of the week.'
complete -c cal -s m -l monday --description 'Display Monday as the first day of the week.'
complete -c cal -s j -l julian --description 'Display Julian dates (days one-based, numbered from January 1).'
complete -c cal -s y -l year --description 'Display a calendar for the whole year.'
complete -c cal -s w -l 'week[' --description 'Display week numbers in the calendar (US or ISO-8601).'
complete -c cal -l 'color[' --description 'Colorize output.'
complete -c cal -s V -l version --description 'Display version information and exit.'
complete -c cal -s h -l help --description 'Display help text and exit.'

