# fsck
# Autogenerated from man page /usr/share/man/man8/fsck.minix.8.gz
# using Deroffing man parser
complete -c fsck -s l --description 'List all filenames.'
complete -c fsck -s r --description 'Perform interactive repairs.'
complete -c fsck -s s --description 'Output super-block information.'
complete -c fsck -s m --description 'Activate MINIX-like "mode not cleared" warnings.'
complete -c fsck -s f --description 'Force a filesystem check even if the filesystem… [See Man Page]'

