# head
# Autogenerated from man page /usr/share/man/man1/head.1.gz
# using Deroffing man parser
complete -c head -s c -l bytes --description 'print the first NUM bytes of each file; with th… [See Man Page]'
complete -c head -s n -l lines --description 'print the first NUM lines instead of the first … [See Man Page]'
complete -c head -s q -l quiet -l silent --description 'never print headers giving file names.'
complete -c head -s v -l verbose --description 'always print headers giving file names.'
complete -c head -s z -l zero-terminated --description 'line delimiter is NUL, not newline.'
complete -c head -l help --description 'display this help and exit.'
complete -c head -l version --description 'output version information and exit.'

