# login
# Autogenerated from man page /usr/share/man/man1/login.1.gz
# using Deroffing man parser
complete -c login -s p --description 'Used by  getty (8) to tell  login not to destro… [See Man Page]'
complete -c login -s f --description 'Used to skip a second login authentication.'
complete -c login -s h --description 'Used by other servers (i. e.'

