# mkshortcut
# Autogenerated from man page /usr/share/man/man1/mkshortcut.1.gz
# using Deroffing man parser
complete -c mkshortcut -s a -l arguments --description 'Arguments to use (see example below).'
complete -c mkshortcut -s d -l desc --description 'Text for description/tooltip (defaults to POSIX… [See Man Page]'
complete -c mkshortcut -s h -l help --description 'Output usage information (to stdout) and exit.'
complete -c mkshortcut -s i -l icon --description 'Specify ICONFILE containing the icon to use for… [See Man Page]'
complete -c mkshortcut -s j -l iconoffset --description 'Requires -i.  Use NUM icon in ICONFILE, offset from 0.'
complete -c mkshortcut -s n -l name --description 'Name to use for the shortcut file.'
complete -c mkshortcut -s s -l show --description 'For norm, min, and max the new window will be n… [See Man Page]'
complete -c mkshortcut -s w -l workingdir --description 'PATH to use for the working directory (defaults… [See Man Page]'
complete -c mkshortcut -s v -l version --description 'Output version information (to stdout) and exit.'
complete -c mkshortcut -s A -l allusers --description 'Requires either -D or -P.'
complete -c mkshortcut -s D -l desktop --description 'Instead of creating the shortcut relative to th… [See Man Page]'
complete -c mkshortcut -s P -l smprograms --description 'Instead of creating the shortcut relative to th… [See Man Page]'

