# readshortcut
# Autogenerated from man page /usr/share/man/man1/readshortcut.1.gz
# using Deroffing man parser
complete -c readshortcut -s h -l help --description 'Output detailed usage information and exit.'
complete -c readshortcut -l usage --description 'Output basic usage information and exit.'
complete -c readshortcut -s v -l version --description 'Display the program version and exit.'
complete -c readshortcut -l license --description 'Display the license agreement and exit.'
complete -c readshortcut -s f -l fields --description 'Show field names (Target, Working Directory, Ar… [See Man Page]'
complete -c readshortcut -s u -l unix --description 'Use Unix path format for display (default).'
complete -c readshortcut -s w -l windows --description 'Use Windows path format for display.'
complete -c readshortcut -s t -l target --description 'Display shortcut target (default).'
complete -c readshortcut -s g -l working --description 'Display shortcut working directory.'
complete -c readshortcut -s r -l args --description 'Display shortcut arguments.'
complete -c readshortcut -s s -l showcmd --description 'Display shortcut "show" command value (Normal, … [See Man Page]'
complete -c readshortcut -s i -l icon --description 'Display icon library location.'
complete -c readshortcut -s j -l offset --description 'Display icon library offset.'
complete -c readshortcut -s d -l desc --description 'Display shortcut description.'
complete -c readshortcut -s a -l all --description 'Display all information.'
complete -c readshortcut -s R -l raw --description 'Show paths in raw mode (that is, without expand… [See Man Page]'

