# run
# Autogenerated from man page /usr/share/man/man1/run.1.gz
# using Deroffing man parser
complete -c run -s p --description 'you can add  path to the PATH environment variable.'
complete -c run -l wait --description 'as first program  argument will make  run  wait… [See Man Page]'
complete -c run -l quote --description 'option enables automatic quoting of arguments w… [See Man Page]'
complete -c run -o wait --description 'and.'
complete -c run -o quote --description 'can be issued with a single leading dash.'

